### PR TITLE
Fix event related unpredicted behaviors

### LINKED ISSUE #184: [PE-D][Tester D] Delete event not deleting correct event
Here I want to delete the first event in the eventlist. But the second event is deleted instead.

<i><video controls><source src="https://raw.githubusercontent.com/chongsun2002/ped/main/files/2bc42cba-08f2-4de9-b98b-2e9b9c35591e.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/chongsun2002/ped/main/files/2bc42cba-08f2-4de9-b98b-2e9b9c35591e.mp4</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chongsun2002/ped#10

### PR DESCRIPTION
**Pull request by youngseopark05**
Fix #184, #169, #147, #153, #159, #154, #170.

### CODE REVIEW

File: src/main/java/seedu/eventfulnus/logic/Messages.java [hunk 1]
```diff
@@ -26,132 +26,6 @@ public class Messages {
             EventfulNUS allows you to manage a list of people and events, for easier event planning for\s
             NUS Inter-Faculty Games.
 
-            These are the available commands:
```
Comment (leowolf275) [inline src/main/java/seedu/eventfulnus/logic/Messages.java:29]: Great that you removed the help pop-up message feature because it was simply too much text

File: src/main/java/seedu/eventfulnus/model/event/Event.java [hunk 2]
```diff
@@ -149,6 +150,7 @@ public boolean isSameEvent(Event otherEvent) {
 
         return otherEvent != null
                 && otherEvent.getName().equals(getName())
+                && otherEvent.getVenue().equals(getVenue())
```
Comment (leowolf275) [inline src/main/java/seedu/eventfulnus/model/event/Event.java:153]: Thanks for adding in the venue!

**Review by leowolf275 — APPROVED** [review]
LGTM!
